### ISSUE TITLE
`webext` CLIENT_SECRET still seems needed 

### ISSUE THREAD

**Issue by JackNUMBER** [fregante/ghatemplates#12]
Reading #10, the `CLIENT_SECRET` env is no longer needed. But I just try the script without it and the error `client_secret is missing` poped. Trying after adding this secret and it pass.

In #11 I proposed to add this secret in the workflow. It was before seeing #10.
Then I created this issue because I probably miss something, and I wanted to be sure.

**Comment by fregante** [comment]
Thank you!
