### ISSUE TITLE
[esm-lint] Do we need to install webpack manually?

### ISSUE THREAD

**Issue by papb** [fregante/ghatemplates#4]
https://github.com/fregante/ghatemplates/blob/ab7a18e468e2f0baf3819ee32e71d9e375c03f30/esm-lint/esm-lint.yml#L35

Or maybe this should be `npx webpack`?

**Comment by fregante** [comment]
No, it uses GitHub Action’s own webpack to speed it up.

**Comment by papb** [comment]
Oh I didn't know GA shipped it's own webpack by default. It does this within `setup-node`?

**Comment by fregante** [comment]
They come with a lot of software by default: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
